# Generated by Django 5.1.4 on 2026-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('order_inquiry', 'Order Inquiry'), ('product_info', 'Product Information'), ('returns', 'Returns & Refunds'), ('technical_support', 'Technical Support'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('order_number', models.CharField(blank=True, help_text='If related to an order', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('washing_machine', 'Washing Machine'), ('dishwasher', 'Dishwasher'), ('oven', 'Oven'), ('refrigerator', 'Refrigerator'), ('dryer', 'Dryer')], max_length=50)),
                ('appliance_brand', models.CharField(max_length=100)),
                ('appliance_model', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('symptoms', models.JSONField(default=list, help_text='List of symptoms selected')),
                ('diagnosis', models.TextField()),
                ('recommended_parts', models.JSONField(default=list, help_text='List of recommended product IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
                'ordering': ['-created_at'],
            },
        ),
    ]
